### ISSUE TITLE
v1 seg faults

### ISSUE THREAD

**Issue by almostEric** [wlaub/vcv#8] opened 2019-08-01 18:17 UTC
Hey! 

These modules seem like they might be pretty fun to play around with. A couple of us other devs just did a build and while they show up in the module browser (a good sign, to be sure!) as soon as you pick a module, VCV crashes. From my experience, this is typically from not initializing a variable.

Anyway, look forward to trying these out!
AlmostEric (Frozen Wasteland)

**Comment by pgatt** [comment] 2019-08-02 07:28
Can confirm this crashes on Mac

**Comment by wlaub** [comment] 2019-08-03 18:40
I'm going to focus on tracking this issue in https://github.com/wlaub/vcv/issues/6, since that was the first report. It looks like the issue is related to Pleaides, which probably does some objectively wrong things from a software engineering POV. There's a (windows) build there that removes Pleiades and seems to work on the computer I was able to reproduce the issue on.

**Comment by wlaub** [comment] 2021-06-10 17:42
Closing since this is tracked in issue #6

**Closed by wlaub** 2021-06-10 17:42 UTC
